version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: perry_eden_postgres
    restart: always
    environment:
      POSTGRES_DB: perry_eden_group
      POSTGRES_USER: perry_user
      POSTGRES_PASSWORD: perry_secure_password_2025
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U perry_user -d perry_eden_group"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: perry_eden_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@perryedengroup.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
